version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - app
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
  app:
    image: leeroyc711/flask:latest
    build: ./service4/
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_IP=${MYSQL_IP}
      - MYSQL_DB=${MYSQL_DB}
      - SECRET_KEY=${SECRET_KEY} 
  service1:
     image: leeroyc711/numbers:latest
     build: ./service1/

  service2:
     image: leeroyc711/letters:latest 
     build: ./service2/

  service3:
     image: leeroyc711/letters-number:latest 
     build: ./service3/


