version: '3.3'
services:
    nginx:
      image: nginx:latest
      ports:
        - target: 80
          published: 80
          protocol: tcp
      depends_on:
        - app
      volumes:
        - type: bind
          source: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
      environment:
        - AWS_XRAY_TRACING_NAME=myapp
        - AWS_XRAY_DAEMON_ADDRESS=x-ray:2000
        - AWS_XRAY_DEBUG_MODE="true"
    app:
      image: flask:latest
      build: 
        context: ./service4
        dockerfile: ../Dockerfile
      ports:
        - target: 5000
          published: 5000
          protocol: tcp
    service1:
       build:
        context: ./service1
        dockerfile: ../Dockerfile
    service2: 
       build: 
        context: ./service2
        dockerfile: ../Dockerfile
    service3: 
       build:
        context: ./service3
        dockerfile: ../Dockerfile
    x-ray:
       container_name: x-ray
       image: amazon/aws-xray-daemon:latest
       ports:
        - "0:2000/udp"


